#!/bin/bash

#SBATCH --job-name=test_random_agent        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8       # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red,brown    # Run on either the Red or Brown queue
#SBATCH --mail-type=END          # Send an email when the job finishes


module load Python/3.8.2-GCCcore-9.3.0
virtualenv venv/$SLURM_JOBID
source venv/$SLURM_JOBID/bin/activate
pip3 install -r requirements.txt

export PYTHONPATH=.
export LC_CTYPE=en_US.UTF-8
export N_ENVS=8

./simulator/run_sims.sh $N_ENVS
sleep 5

FLAGS="--job_id $SLURM_JOBID --n_envs $N_ENVS"

if [ -n "$RANDOM_SEED" ]; then
    FLAGS= "$FLAGS --seed $RANDOM_SEED"
fi

python3 collect_rollouts.py $FLAGS $LEVEL_ID
