#!/bin/bash

#SBATCH --job-name=test_random_agent        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8       # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red,brown    # Run on either the Red or Brown queue

source venv/bin/activate
pip3 install -r requirements.txt
export PYTHONPATH=.
export LC_CTYPE=en_US.UTF-8

simulator/linux.x86_64 &
sleep 5

if [ -n "$RANDOM_SEED" ]; then
  python3 collect_rollouts.py --job_id $SLURM_JOBID --seed $RANDOM_SEED $LEVEL_ID
else
  python3 collect_rollouts.py --job_id $SLURM_JOBID $LEVEL_ID
fi
